server:
  port: 8083

spring:
  application:
    name: evolve-admin-api

  # ----- DataSource -----
  datasource:
    url: jdbc:mysql://localhost:3306/evolve_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

# ----- MyBatis-Plus -----
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# ----- Actuator -----
management:
  endpoints:
    web:
      exposure:
        include: health,info
